quarkus:
  application:
    name: quickstart
  live-reload:
    instrumentation: true
  #  native:
#    enabled: true
  package:
    jar:
      type: fast-jar
  jackson:
    fail-on-unknown-properties: false
    fail-on-empty-beans: true